### ISSUE TITLE
knockout 3.x

### ISSUE THREAD

**Issue by villanus** [finnsson/pagerjs#179]
does pager work on knockout 3 versions?  also is there a way to use history plugin wihtout seeting base url in html?

**Comment by dmayo3** [comment]
It works for me on version 3.2.0 but having issues with 3.3.0

Most of the page is not rendering, but I'm not sure exactly what's triggering it.

Here's the stack trace:

    Uncaught TypeError: Cannot read property 'foo' of null
    (anonymous function)                            @ pager.js:638
    jQuery.extend.each                              @ jquery.js:648
    p.setParams                                     @ pager.js:636
    p.showPage                                      @ pager.js:607
    pager.ChildManager.showChild.showCurrentChild   @ pager.js:304
    pager.ChildManager.showChild                    @ pager.js:319
    p.showPage                                      @ pager.js:619
    pager.ChildManager.showChild.showCurrentChild   @ pager.js:304
    pager.ChildManager.showChild                    @ pager.js:319
    p.showPage                                      @ pager.js:619
    pager.showChild                                 @ pager.js:81
    goTo                                            @ pager.js:123
    pager.start.onHashChange                        @ pager.js:1482
    pager.start                                     @ pager.js:1487

**Comment by DKhalil** [comment]
Current version tested and working with 3.4.*. If you're still having troubles open a new issue please
