### ISSUE TITLE
Backbone.history

### ISSUE THREAD

**Issue by far-blue** [finnsson/pagerjs#186]
Is there any documentation or an interface available for using alternative history libraries? I've already got Backbone.js in my project and it has built-in support for history tracking (inc. html5 urls) so it would be sensible to use it if I can.

**Comment by villanus** [comment]
knockback js does this

**Comment by far-blue** [comment]
Do you mean Knockback offers pager-style functionality? Or it integrates with Pager? I've used Knockback and Pager together on a few apps and like the combination but I've not found how to integrate Backbone or Knockback history management into Pager meaning, unless I want to include yet another library I'm left with #tag style history tracking. Hence my original question :) Knockback itself doesn't have paging support but the developers have produced a stand-alone framework to integrate it. However, I prefer Pager.
