### ISSUE TITLE
Dividing a page into "fragments"?

### ISSUE THREAD

**Issue by slisznia** [finnsson/pagerjs#193]
Hi All,

I was curious if you have a strategy for dividing a longer page into sections or fragments, each having its own model and all displayed at the same time. In other words, a fragment would work almost like your "page" except that it would co-exist with other "pages" shown at the same time. Ideally then, a pagerjs page could host one or more such fragments.

When the page is displayed, all its fragments' withOnShow calls would be made, so each fragment could fetch its data. It would also be easier to later re-organize fragments into distinct pages or tabs.

Thanks!

**Comment by finnsson** [comment]
I haven't tried this scenario myself and unsure how difficult it would be to extend pager to handle it. You could probably solve it with some coding using `urlToggle: none`  and programmatically displaying the pages. Another alternative could be to add extend pager in some way. Pull requests are welcome.

**Comment by gilesbradshaw** [comment]
Sounds a bit like knockout components?
