### ISSUE TITLE
Apply routes from JavaScript

### ISSUE THREAD

**Issue by insonifi** [finnsson/pagerjs#194]
Hi, I'm researching routing possibilities with Knockout, and pagerjs in particular. Documentation only describes routes declaration in data-bind attribute. Is there a way to apply routes from JavaScript?

**Comment by finnsson** [comment]
There is no way to apply routes from JavaScript at the moment. The routing is not centralised in the same way as in other SPA libraries/frameworks.

**Comment by insonifi** [comment]
Do you think it can be useful for pagerjs?
