### ISSUE TITLE
how to use pager.navigate to go to a relative-parent?

### ISSUE THREAD

**Issue by slisznia** [finnsson/pagerjs#199]
I have a modal page with a form. When a user submits the form, I wish to send him back to a relative-parent of the modal via pager.navigate(<relative parent path>) 

My approach is to refer to currentParentPath:

    pager.navigate(page.currentParentPath());

**Comment by stiff** [comment]
It would be nice if `pager.navigate` understands the '../' for this

**Comment by umartopia** [comment]
any suggested way to accomplish this?
