### ISSUE TITLE
Node dependencies and development status

### ISSUE THREAD

**Issue by akuz** [finnsson/pagerjs#206]
Hi, this library is simply awesome! 
(I am investigating using Knockout instead of Angular.)

When I install `pagerjs` via `npm`, it has a dependency on jQuery but not on Knockout.

Questions:
1) Does pagerjs come with it's own version of jQuery (will this increase my code base if I also use another version of jQuery)?
2) Why does it not depend on Knockout? For example, how do I know which versions of Knockout a particular version of this library can work with?
3) Also I don't see too much development going on, but I can trust this is still the best solution you personally use at the moment, and the functionality just stabilised? Or everybody else moved on to something else?

Thank you in advance. Sorry, I cannot tag this issue with `question` by myself.

**Comment by finnsson** [comment]
Hi,

I haven't updated the npm-package for quite some time. It caused some confusion (developers thought it was a node.js-package). I'd recommend you to use the file in the dist-folder (https://github.com/finnsson/pagerjs/tree/master/dist).

The development is not active on my part. It's used in production in some products and it's solving my problems. You are always welcome to send pull requests :)

**Comment by akuz** [comment]
Hi, thanks for your reply. Yes, I saw stackoverflow question from someone asking why then need npm to use pagerjs... But it doesn't mean it's not worth to publish it there since it is convenient to load it using require() and then minify it together with the rest of the code... Anyway, I guess bower is fine,  thank you!
