### ISSUE TITLE
Pagerjs not working with require

### ISSUE THREAD

**Issue by karenpommeroy** [finnsson/pagerjs#221]
No matter what I do pager is always empty (even though I can see that pager.min,js is grabbed from the server):

equire.config({
    paths: {
        "jquery": "lib/jquery/jquery-2.2.0.min",
        "pagerjs": "lib/pagerjs/pager",
        "knockout": "lib/knockout/knockout-3.4.0",
    },
    shim : {
        "pagerjs": ["jquery", "knockout"]
    },

```
waitSeconds: 30
```

});

require([
  "pagerjs"
], function(pg){

// Here pg is awlays undefined

});

**Comment by Olliebaba** [comment]
Have you looked at how it's configured in the [pagerjs repo](https://github.com/finnsson/pagerjs/blob/master/pagerjs.com/demo/demo.js)? Looks like you don't need to shim pager.
